import { createFileRoute } from "@tanstack/react-router";
import { SiteNav } from "@/components/site-nav";
import { ShieldCheck, MapPin, Radio, Camera, Fingerprint, Lock } from "lucide-react";
import { StudentSidebar } from "@/components/student-sidebar";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "About Sentinel — Sentinel.edu" },
      {
        name: "description",
        content: "How Sentinel protects the integrity of university attendance.",
      },
    ],
  }),
  component: AboutPage,
});

function AboutPage() {
  return (
    <div className="flex min-h-screen bg-background">
      <StudentSidebar />
      <div className="min-w-0 flex-1">
        <main className="mx-auto max-w-7xl px-6 py-10 lg:p-10">
          <header className="mb-10 flex flex-wrap items-end justify-between gap-4">
            <div>
              <div className="text-[10px] font-bold uppercase tracking-[0.2em] text-primary">
                System Documentation
              </div>
              <h1 className="mt-2 text-4xl font-semibold tracking-tight">How Sentinel Works</h1>
              <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
                Sentinel uses cryptographic hashing, rolling sessions, and geolocation to ensure that attendance data is accurate and verifiable.
              </p>
            </div>
          </header>

          <div className="grid gap-10 lg:grid-cols-2">
            <div className="space-y-6">
              <div className="rounded-2xl border border-border bg-card/40 p-6 sm:p-8">
                <h2 className="text-xl font-semibold tracking-tight mb-4 flex items-center gap-2">
                  <ShieldCheck className="size-5 text-primary" /> Core Security Features
                </h2>
                
                <div className="space-y-6 mt-6">
                  <div className="flex gap-4">
                    <div className="mt-1 flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                      <Camera className="size-4" />
                    </div>
                    <div>
                      <h3 className="font-semibold text-sm">Native Camera Integration</h3>
                      <p className="text-sm text-muted-foreground mt-1">There is no in-app scanner. You use your phone's native camera to scan the Lecturer's QR code, routing you directly to the secure verification portal.</p>
                    </div>
                  </div>

                  <div className="flex gap-4">
                    <div className="mt-1 flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                      <Lock className="size-4" />
                    </div>
                    <div>
                      <h3 className="font-semibold text-sm">Rolling QR Sessions</h3>
                      <p className="text-sm text-muted-foreground mt-1">The QR code generated by the lecturer rotates cryptographic keys every 90 seconds. A photo of the QR code sent to a friend will expire before they can use it.</p>
                    </div>
                  </div>

                  <div className="flex gap-4">
                    <div className="mt-1 flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                      <MapPin className="size-4" />
                    </div>
                    <div>
                      <h3 className="font-semibold text-sm">Geofencing & Location Proof</h3>
                      <p className="text-sm text-muted-foreground mt-1">Your GPS coordinates are matched against the physical boundaries of the lecture hall. You cannot mark attendance from the dorm.</p>
                    </div>
                  </div>

                  <div className="flex gap-4">
                    <div className="mt-1 flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                      <Fingerprint className="size-4" />
                    </div>
                    <div>
                      <h3 className="font-semibold text-sm">Device Fingerprinting</h3>
                      <p className="text-sm text-muted-foreground mt-1">We analyze the device footprint to prevent one student from bringing multiple phones to class to scan for their friends.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="space-y-6">
              <div className="rounded-2xl border border-border glass p-8">
                <h3 className="text-lg font-semibold flex items-center gap-2">
                  <Radio className="size-5 text-success" /> The Verification Flow
                </h3>
                <ol className="mt-6 space-y-5 text-sm text-muted-foreground">
                  <li className="flex gap-4">
                    <span className="flex size-7 shrink-0 items-center justify-center rounded-full border border-primary/30 bg-primary/10 text-[11px] font-bold text-primary">
                      1
                    </span>
                    <span className="leading-relaxed">Faculty initiates a session on their dashboard and projects the QR code.</span>
                  </li>
                  <li className="flex gap-4">
                    <span className="flex size-7 shrink-0 items-center justify-center rounded-full border border-primary/30 bg-primary/10 text-[11px] font-bold text-primary">
                      2
                    </span>
                    <span className="leading-relaxed">Students open their phone's native camera and scan the code.</span>
                  </li>
                  <li className="flex gap-4">
                    <span className="flex size-7 shrink-0 items-center justify-center rounded-full border border-primary/30 bg-primary/10 text-[11px] font-bold text-primary">
                      3
                    </span>
                    <span className="leading-relaxed">The network intercepts the request, verifying the AES-256 session signature.</span>
                  </li>
                  <li className="flex gap-4">
                    <span className="flex size-7 shrink-0 items-center justify-center rounded-full border border-primary/30 bg-primary/10 text-[11px] font-bold text-primary">
                      4
                    </span>
                    <span className="leading-relaxed">GPS and device metadata are verified server-side.</span>
                  </li>
                  <li className="flex gap-4">
                    <span className="flex size-7 shrink-0 items-center justify-center rounded-full border border-primary/30 bg-primary/10 text-[11px] font-bold text-primary">
                      5
                    </span>
                    <span className="leading-relaxed">The immutable ledger is updated, reflecting instantly on the faculty's live stream.</span>
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
